filter:
    excluded_paths:
        - 'test/*'
        - 'vendor/*'
        - 'samples/*'
        
environment:
        php: 7.0
        
checks:
    php: true
    
coding_style:
    php: {  }

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'php-clover'